routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/artisan/{command}', function ($command) {
    return \Illuminate\Support\Facades\Artisan::call($command);
});

Route::get("/test","SiteController@test");

Route::get("/oauth/auth","YandexAuthController@auth");
Route::get("/oauth/start","YandexAuthController@start")->name('oauth.start');;

Route::get('/', function () {
    return redirect(url("/sites"));
});

Route::get("/sites/report/{id}","SiteController@report")->name("site.report");
Route::get("/sites/metrika","SiteController@metrika")->name("site.metrika");
Route::resource('sites', 'SiteController');

Route::group(["prefix" => "report"], function() {
    Route::get("html/{idSite}","ReportController@html")->name("report.html");
    Route::get("word/{idSite}","ReportController@word")->name("report.word");
    Route::get("pdf/{idSite}","ReportController@pdf")->name("report.pdf");
    Route::get("changeDate","ReportController@change_date")->name("report.changeDatePeriod");
});

Route::group(["prefix" => "history"], function() {
    Route::get("download/{id}","ReportHistoryController@download")->name("history.download");
    Route::get("delete/{id}","ReportHistoryController@delete")->name("history.delete");
});

Route::group(["prefix" => "reportPart"], function() {
    Route::post("save","ReportPartController@save")->name("reportPart.save");
    Route::get("params","ReportPartController@default_params")->name("reportPart.params");
    Route::get("{id}","ReportPartController@update")->name("reportPart.update");
});

Route::group(["prefix" => "template"], function() {
    Route::post("save","TemplateController@save");
    Route::get("load","TemplateController@load");
});
Route::resource('template', 'TemplateController');

Route::post('requests/import', 'SearchRequestController@import')->name('requests.import');
Route::resource('requests', 'SearchRequestController');

Route::resource('regions', 'RegionController');

resources/views/template/index.blade.php
@extends('layouts.app')

@section('content')
        <h1 class="pull-left">Шаблоны отчетов</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('template.create') !!}">Add New</a>

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        @include('template.table')
        
@endsection

resources/views/template/table.blade.php
<table class="table table-responsive" id="template-table">
    <thead>
        <th style="width: 20%">Name</th>
        <th>Шаблон</th>
        <th style="width: 10%">Action</th>
    </thead>
    <tbody>
    @foreach($templates as $template)
        <tr>
            <td>{!! $template->name !!}</td>
            <td>
                <select data-id = "{!! $template->id !!}" multiple data-placeholder = "Содержимое шаблона..." class="js-chosen" style="width: 100%">
                    @foreach( $reportParts as $part)
                        <option @if($template->hasPart($part)) selected @endif value = {!! $part->getId() !!}>{!! $part->name !!}</option>
                    @endforeach
                </select>
            </td>
            <td>
                {!! Form::open(['route' => ['template.destroy', $template->id], 'method' => 'delete']) !!}
                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<script>
    $(document).ready(function() {
        $(".js-chosen").chosen({disable_search_threshold: 10}).change(function(a,b,c) {
            saveChange(this);
        });
    });

    function saveChange(select)
    {
        let id = $(select).data("id");
        let value = $(select).val().join(",");
        aja()
            .method('post')
            .url(window.Laravel.basePath+"/template/save")
            .data({_token: window.Laravel.csrfToken, id: id, content: value})
            .on('200', (e) => {
                onSaveChange();
            })
            .go()
    }

    function onSaveChange() {

    }

</script>